<?php

/**
 * @file
 * Install, update and uninstall functions for the U-M CKEditor Improvements module.
 */


function um_cke_improvements_update_10001() {
  $templates = [
        [
          "title" => "Alert",
          "icon" => "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\"><!--!Font Awesome Pro v7.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2026 Fonticons, Inc.--><path d=\"M320.5 64C335.2 64 348.7 72.1 355.7 85L571.7 485C578.4 497.4 578.1 512.4 570.9 524.5C563.7 536.6 550.6 544 536.5 544L104.5 544C90.4 544 77.4 536.6 70.2 524.5C63 512.4 62.7 497.4 69.4 485L285.4 85C292.4 72.1 305.9 64 320.6 64zM117.9 496L523.1 496L320.5 120.8L117.9 496zM320.5 456C302.8 456 288.5 441.7 288.5 424C288.5 406.3 302.8 392 320.5 392C338.2 392 352.5 406.3 352.5 424C352.5 441.7 338.2 456 320.5 456zM320.5 248C339.1 248 353.5 264.1 351.5 282.6L344.4 346.7C343 358.8 332.7 368 320.5 368C308.3 368 298 358.8 296.7 346.7L289.6 282.6C287.6 264.1 302 248 320.6 248z\"/></svg>",
          "description" => "Insert a Bootstrap Alert.",
          "html" => "<div class=\"alert alert-info\" role=\"alert\">Alert Message</div>"
        ],
        [
          "title" => "Panel with heading",
          "icon" => "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\"><!--!Font Awesome Pro v7.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2026 Fonticons, Inc.--><path d=\"M112 448L112 320L528 320L528 448C528 456.8 520.8 464 512 464L128 464C119.2 464 112 456.8 112 448zM128 128C92.7 128 64 156.7 64 192L64 448C64 483.3 92.7 512 128 512L512 512C547.3 512 576 483.3 576 448L576 192C576 156.7 547.3 128 512 128L128 128zM160 192C177.7 192 192 206.3 192 224C192 241.7 177.7 256 160 256C142.3 256 128 241.7 128 224C128 206.3 142.3 192 160 192zM224 224C224 206.3 238.3 192 256 192C273.7 192 288 206.3 288 224C288 241.7 273.7 256 256 256C238.3 256 224 241.7 224 224zM352 192C369.7 192 384 206.3 384 224C384 241.7 369.7 256 352 256C334.3 256 320 241.7 320 224C320 206.3 334.3 192 352 192z\"/></svg>",
          "description" => "Insert a panel with a heading.",
          "html" => "<div class=\"panel panel-default\">\n  <div class=\"panel-heading\"><h2>Panel heading</h2></div>\n  <div class=\"panel-body\">\n    Panel content\n  </div>\n</div>\n<p> &nbsp;</p>"
        ],
        [
          "title" => "Panel",
          "icon" => "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\"><!--!Font Awesome Free v7.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2026 Fonticons, Inc.--><path d=\"M112 288L112 448C112 456.8 119.2 464 128 464L512 464C520.8 464 528 456.8 528 448L528 288L112 288zM64 192C64 156.7 92.7 128 128 128L512 128C547.3 128 576 156.7 576 192L576 448C576 483.3 547.3 512 512 512L128 512C92.7 512 64 483.3 64 448L64 192z\"/></svg>",
          "description" => "Insert a panel.",
          "html" => "<div class=\"panel panel-default\">\n  <div class=\"panel-heading\">Panel header</div>\n  <div class=\"panel-body\">\n    Panel content\n  </div>\n</div>\n<p> &nbsp;</p>"
        ],
        [
          "title" => "2 column layout",
          "icon" => "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\">\n  <line x1=\"3\" y1=\"6\" x2=\"10\" y2=\"6\"/>\n  <line x1=\"3\" y1=\"10\" x2=\"10\" y2=\"10\"/>\n  <line x1=\"3\" y1=\"14\" x2=\"10\" y2=\"14\"/>\n  <line x1=\"3\" y1=\"18\" x2=\"10\" y2=\"18\"/>\n\n  <line x1=\"14\" y1=\"6\" x2=\"21\" y2=\"6\"/>\n  <line x1=\"14\" y1=\"10\" x2=\"21\" y2=\"10\"/>\n  <line x1=\"14\" y1=\"14\" x2=\"21\" y2=\"14\"/>\n  <line x1=\"14\" y1=\"18\" x2=\"21\" y2=\"18\"/>\n</svg>",
          "description" => "Insert two columns.",
          "html" => "<div class=\"row\">\n    <div class=\"col-sm-6\">\n      One of two columns\n    </div>\n    <div class=\"col-sm-6\">\n      two of two columns\n    </div>\n  </div>\n<p> &nbsp; </p>"
        ],
        [
          "title" => "3 column layout",
          "icon" => "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" xmlns=\"http://www.w3.org/2000/svg\">\n  <!-- col 1 -->\n  <line x1=\"2\" y1=\"6\" x2=\"6\" y2=\"6\"/>\n  <line x1=\"2\" y1=\"10\" x2=\"6\" y2=\"10\"/>\n  <line x1=\"2\" y1=\"14\" x2=\"6\" y2=\"14\"/>\n  <line x1=\"2\" y1=\"18\" x2=\"6\" y2=\"18\"/>\n\n  <!-- col 2 -->\n  <line x1=\"10\" y1=\"6\" x2=\"14\" y2=\"6\"/>\n  <line x1=\"10\" y1=\"10\" x2=\"14\" y2=\"10\"/>\n  <line x1=\"10\" y1=\"14\" x2=\"14\" y2=\"14\"/>\n  <line x1=\"10\" y1=\"18\" x2=\"14\" y2=\"18\"/>\n\n  <!-- col 3 -->\n  <line x1=\"18\" y1=\"6\" x2=\"22\" y2=\"6\"/>\n  <line x1=\"18\" y1=\"10\" x2=\"22\" y2=\"10\"/>\n  <line x1=\"18\" y1=\"14\" x2=\"22\" y2=\"14\"/>\n  <line x1=\"18\" y1=\"18\" x2=\"22\" y2=\"18\"/>\n</svg>",
          "description" => "Insert two columns.",
          "html" => "<div class=\"row\">\n    <div class=\"col-sm-4\">\n      One of three columns\n    </div>\n    <div class=\"col-sm-4\">\n      two of three columns\n    </div>\n    <div class=\"col-sm-4\">\n      three of three columns\n    </div>\n  </div>\n<p> &nbsp; </p>"
        ],
        [
          "title" => "Jumbotron",
          "icon" => "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\"><!--!Font Awesome Pro v7.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2026 Fonticons, Inc.--><path d=\"M64 192C64 156.7 92.7 128 128 128L512 128C547.3 128 576 156.7 576 192L576 448C576 483.3 547.3 512 512 512L128 512C92.7 512 64 483.3 64 448L64 192z\"/></svg>",
          "description" => "Insert two columns.",
          "html" => "<div class=\"jumbotron\">\n  <h2>Title</h2>\n  <p>Descriptive body copy</p>\n  <p><a class=\"btn btn-primary btn-large\" href=\"#\" role=\"button\">Learn more</a></p>\n</div>\n<p> &nbsp; </p>"
        ]
      ];

  foreach ($templates as $template) {
    $template_entity = \Drupal::entityTypeManager()
      ->getStorage('ckeditor5_template')
      ->create([
        'id' => strtolower(str_replace(' ', '_', $template['title'])),
        'title' => $template['title'],
        'icon' => $template['icon'],
        'description' => $template['description'],
        'allowed_text_formats' => ['full_html', 'filtered_html'],
        'html' => $template['html']
      ]);
    $template_entity->save();
  }
}
